#include "emit.h"

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

void idl_write(struct idl_writer *writer, const char *format, ...) {
    va_list arguments;
    size_t remaining;
    int written;

    if (writer->overflowed) {
        return;
    }

    remaining = writer->capacity - writer->length;

    va_start(arguments, format);
    written = vsnprintf(writer->buffer + writer->length, remaining, format,
                        arguments);
    va_end(arguments);

    if ((written < 0) || ((size_t)written >= remaining)) {
        writer->overflowed = 1;
        writer->buffer[writer->length] = '\0';
        return;
    }

    writer->length += (size_t)written;
}

const char *idl_type_name(enum idl_type type) {
    switch (type) {
    case IDL_TYPE_I32:
        return "i32";
    case IDL_TYPE_U32:
        return "u32";
    case IDL_TYPE_I64:
        return "i64";
    case IDL_TYPE_U64:
        return "u64";
    case IDL_TYPE_SLICE_U8:
        return "slice<u8>";
    case IDL_TYPE_CAP:
        return "cap";
    case IDL_TYPE_CAP_OPT:
        return "cap?";
    case IDL_TYPE_PTR_I32:
        return "ptr<i32>";
    case IDL_TYPE_TYPE_ID:
        return "type-id";
    case IDL_TYPE_OBJECT_REF:
        return "object-ref";
    case IDL_TYPE_VOID:
    default:
        return "void";
    }
}

static const char *parameter_letters(enum idl_type type) {
    switch (type) {
    case IDL_TYPE_SLICE_U8:
        return "ii";
    case IDL_TYPE_TYPE_ID:
        return "II";
    case IDL_TYPE_I64:
    case IDL_TYPE_U64:
        return "I";
    default:
        return "i";
    }
}

static const char *result_letter(enum idl_type type) {
    switch (type) {
    case IDL_TYPE_I64:
    case IDL_TYPE_U64:
        return "I";
    case IDL_TYPE_VOID:
        return "";
    default:
        return "i";
    }
}

int idl_wamr_signature(
    const struct idl_syscall *syscall,
    char *out,
    size_t capacity
) {
    size_t used = 0;
    size_t index;

    if (capacity == 0) {
        return 0;
    }

    out[used] = '\0';

    if ((used + 1u) >= capacity) {
        return 0;
    }
    out[used] = '(';
    used += 1;

    for (index = 0; index < syscall->param_count; index++) {
        const char *letters = parameter_letters(syscall->params[index].type);
        size_t letter_count = strlen(letters);

        if ((used + letter_count) >= capacity) {
            out[0] = '\0';
            return 0;
        }
        memcpy(out + used, letters, letter_count);
        used += letter_count;
    }

    if ((used + 1u) >= capacity) {
        out[0] = '\0';
        return 0;
    }
    out[used] = ')';
    used += 1;

    {
        const char *result = result_letter(syscall->result);
        size_t result_count = strlen(result);

        if ((used + result_count) >= capacity) {
            out[0] = '\0';
            return 0;
        }
        memcpy(out + used, result, result_count);
        used += result_count;
    }

    out[used] = '\0';
    return 1;
}

int idl_emit_table(const struct idl_unit *unit, struct idl_writer *writer) {
    size_t index;

    idl_write(writer,
              "/* GENERATED by tools/idlc - do not edit. */\n\n"
              "static NativeSymbol jani_symbols[] = {\n");

    for (index = 0; index < unit->syscall_count; index++) {
        const struct idl_syscall *syscall = &unit->syscalls[index];
        char signature[64];

        if (!idl_wamr_signature(syscall, signature, sizeof(signature))) {
            return 0;
        }

        idl_write(writer,
                  "    { \"jani_%s\", (void *)jani_%s_impl, \"%s\", NULL },\n",
                  syscall->name, syscall->name, signature);
    }

    idl_write(writer, "};\n");

    return writer->overflowed ? 0 : 1;
}
