#include "emit.h"

#include <string.h>

static const char *zig_result(enum idl_type type) {
    switch (type) {
    case IDL_TYPE_I64:
    case IDL_TYPE_U64:
        return "i64";
    case IDL_TYPE_VOID:
        return "void";
    default:
        return "i32";
    }
}

static const char *zig_scalar(enum idl_type type) {
    switch (type) {
    case IDL_TYPE_U32:
        return "u32";
    case IDL_TYPE_I64:
        return "i64";
    case IDL_TYPE_U64:
        return "u64";
    case IDL_TYPE_OUT_I32:
        return "?*i32";
    default:
        return "i32";
    }
}

static void emit_extern_params(
    struct idl_writer *writer,
    const struct idl_syscall *syscall
) {
    size_t index;

    for (index = 0; index < syscall->param_count; index++) {
        const struct idl_param *param = &syscall->params[index];

        if (index != 0) {
            idl_write(writer, ", ");
        }

        switch (param->type) {
        case IDL_TYPE_SLICE_U8:
            idl_write(writer, "%s_ptr: [*]const u8, %s_len: u32",
                      param->name, param->name);
            break;
        case IDL_TYPE_SLICE_U8_OUT:
            idl_write(writer, "%s_ptr: [*]u8, %s_len: u32",
                      param->name, param->name);
            break;
        case IDL_TYPE_TYPE_ID:
            idl_write(writer, "%s_high: i64, %s_low: i64",
                      param->name, param->name);
            break;
        default:
            idl_write(writer, "%s: %s", param->name, zig_scalar(param->type));
            break;
        }
    }
}

static void emit_wrapper_params(
    struct idl_writer *writer,
    const struct idl_syscall *syscall
) {
    size_t index;

    for (index = 0; index < syscall->param_count; index++) {
        const struct idl_param *param = &syscall->params[index];

        if (index != 0) {
            idl_write(writer, ", ");
        }

        switch (param->type) {
        case IDL_TYPE_SLICE_U8:
            idl_write(writer, "%s: []const u8", param->name);
            break;
        case IDL_TYPE_SLICE_U8_OUT:
            idl_write(writer, "%s: []u8", param->name);
            break;
        case IDL_TYPE_TYPE_ID:
            idl_write(writer, "%s_high: i64, %s_low: i64",
                      param->name, param->name);
            break;
        default:
            idl_write(writer, "%s: %s", param->name, zig_scalar(param->type));
            break;
        }
    }
}

static void emit_forwarded_args(
    struct idl_writer *writer,
    const struct idl_syscall *syscall
) {
    size_t index;

    for (index = 0; index < syscall->param_count; index++) {
        const struct idl_param *param = &syscall->params[index];

        if (index != 0) {
            idl_write(writer, ", ");
        }

        switch (param->type) {
        case IDL_TYPE_SLICE_U8:
        case IDL_TYPE_SLICE_U8_OUT:
            idl_write(writer, "%s.ptr, @intCast(%s.len)",
                      param->name, param->name);
            break;
        case IDL_TYPE_TYPE_ID:
            idl_write(writer, "%s_high, %s_low", param->name, param->name);
            break;
        default:
            idl_write(writer, "%s", param->name);
            break;
        }
    }
}

int idl_emit_zig(const struct idl_unit *unit, struct idl_writer *writer) {
    size_t index;

    idl_write(writer, "// GENERATED by tools/idlc - do not edit.\n\n");

    for (index = 0; index < unit->syscall_count; index++) {
        const struct idl_syscall *syscall = &unit->syscalls[index];

        idl_write(writer, "extern \"env\" fn jani_%s(", syscall->name);
        emit_extern_params(writer, syscall);
        idl_write(writer, ") %s;\n", zig_result(syscall->result));
    }

    idl_write(writer, "\n");

    for (index = 0; index < unit->syscall_count; index++) {
        const struct idl_syscall *syscall = &unit->syscalls[index];
        const char *result = zig_result(syscall->result);

        idl_write(writer, "pub fn %s(", syscall->name);
        emit_wrapper_params(writer, syscall);
        idl_write(writer, ") %s {\n", result);

        if (syscall->result == IDL_TYPE_VOID) {
            idl_write(writer, "    jani_%s(", syscall->name);
        } else {
            idl_write(writer, "    return jani_%s(", syscall->name);
        }
        emit_forwarded_args(writer, syscall);
        idl_write(writer, ");\n}\n\n");
    }

    return writer->overflowed ? 0 : 1;
}
