#include "emit.h"

static const char *c_result(enum idl_type type) {
    switch (type) {
    case IDL_TYPE_I64:
    case IDL_TYPE_U64:
        return "int64_t";
    case IDL_TYPE_VOID:
        return "void";
    default:
        return "int32_t";
    }
}

static const char *c_scalar(enum idl_type type) {
    switch (type) {
    case IDL_TYPE_U32:
    case IDL_TYPE_PTR_I32:
        return "uint32_t";
    case IDL_TYPE_I64:
        return "int64_t";
    case IDL_TYPE_U64:
        return "uint64_t";
    default:
        return "int32_t";
    }
}

int idl_emit_c(const struct idl_unit *unit, struct idl_writer *writer) {
    size_t index;

    idl_write(writer,
              "/* GENERATED by tools/idlc - do not edit. */\n\n"
              "#ifndef JANI_SDK_C_JANI_H\n"
              "#define JANI_SDK_C_JANI_H\n\n"
              "#include <stdint.h>\n\n");

    for (index = 0; index < unit->syscall_count; index++) {
        const struct idl_syscall *syscall = &unit->syscalls[index];
        size_t param;

        idl_write(writer, "%s jani_%s(", c_result(syscall->result),
                  syscall->name);

        if (syscall->param_count == 0) {
            idl_write(writer, "void");
        }

        for (param = 0; param < syscall->param_count; param++) {
            const struct idl_param *current = &syscall->params[param];

            if (param != 0) {
                idl_write(writer, ", ");
            }

            switch (current->type) {
            case IDL_TYPE_SLICE_U8:
            case IDL_TYPE_SLICE_U8_OUT:
                idl_write(writer, "uint32_t %s_ptr, uint32_t %s_len",
                          current->name, current->name);
                break;
            case IDL_TYPE_TYPE_ID:
                idl_write(writer, "int64_t %s_high, int64_t %s_low",
                          current->name, current->name);
                break;
            default:
                idl_write(writer, "%s %s", c_scalar(current->type),
                          current->name);
                break;
            }
        }

        idl_write(writer, ");\n");
    }

    idl_write(writer, "\n#endif\n");

    return writer->overflowed ? 0 : 1;
}
