#include "emit.h"

int idl_emit_conform(const struct idl_unit *unit, struct idl_writer *writer) {
    size_t index;

    idl_write(writer,
              "/* GENERATED by tools/idlc - do not edit. */\n\n"
              "#ifndef JANI_KERNEL_WASM_GENERATED_RECORDS_CONFORM_H\n"
              "#define JANI_KERNEL_WASM_GENERATED_RECORDS_CONFORM_H\n\n"
              "#include <stddef.h>\n\n");

    for (index = 0; index < unit->record_count; index++) {
        const struct idl_record *record = &unit->records[index];
        size_t field;

        for (field = 0; field < record->field_count; field++) {
            const struct idl_field *current = &record->fields[field];

            idl_write(writer,
                      "_Static_assert(\n"
                      "    offsetof(struct %s, %s) == %llu,\n"
                      "    \"%s.%s moved; update idl/records.idl\"\n"
                      ");\n",
                      record->name, current->name,
                      (unsigned long long)current->offset,
                      record->name, current->name);
        }

        idl_write(writer,
                  "_Static_assert(\n"
                  "    sizeof(struct %s) == %llu,\n"
                  "    \"%s changed size; update idl/records.idl\"\n"
                  ");\n\n",
                  record->name, (unsigned long long)record->size,
                  record->name);
    }

    idl_write(writer, "#endif\n");

    return writer->overflowed ? 0 : 1;
}
